name: stitch
on:
  push:
    branches: [ "main" ]
    paths: [ "*.sql" ]
  pull_request:
    branches: [ "main" ]
    paths: [ "*.sql" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run stitching script
        run: ./stitch.sh tests/**/*.sql > acid.sql
      - name: Check it does not deviate
        run: git diff --exit-code
      - name: Upload stitched result
        uses: actions/upload-artifact@v3
        with:
          name: acid
          path: acid.sql
