name: stitch
on:
  push:
    branches: [ "main" ]
    paths: [ "sql/*.sql" ]
  pull_request:
    branches: [ "main" ]
    paths: [ "sql/*.sql" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run stitching script
        run: ./stitch.sh sql/test* > acid.sql
      - name: Upload stitched result
        uses: actions/upload-artifact@v3
        with:
          name: acid
          path: acid.sql
  check:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: acid
          path: _acid.sql
      - name: Run stitching script
        run: git diff --exit-code _acid.sql acid.sql
